image: node:latest

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 day
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - build
  script:
    - npm run test:coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

release:
  image: node:latest
  dependencies:
    - test
  stage: release
  only:
    refs:
      - main
      - /^(([0-9]+)\.)?([0-9]+)\.x/
      - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/

  script:
    - touch CHANGELOG.md
    - npm install @semantic-release/git
    - npm install @semantic-release/gitlab
    - npm install @semantic-release/changelog
    - npm install @semantic-release/npm
    - npx semantic-release
